version: '3'
services:
  web:
    build: ./web
    restart: always
    ports:
      - "8888:3000"

  search:
    build: ./search
    restart: always
    # ports: 
    #   - "1111:1111" # enable for running/testing service individually

  charts:
    build: ./charts
    restart: always
    # ports:
    #   - "2222:2222" # enable for running/testing service individually

  images:
    build: ./images
    restart: always
    # ports:
    #   - "3333:8080" # enable for running/testing service individually
